### PR TITLE
created django site, no apps yet

### PR DESCRIPTION
**Pull request by aelkner**
This first pull request only has the initial change to add the empty django site.

### CODE REVIEW

**Comment by cgreene** [comment]
Thanks @aelkner! Looks like requirements is django 1.9+ which is good since it gets us the access to in database JSON support that @awm33 mentioned in https://github.com/cognoma/cognoma/issues/5

@dhimmel: I am not a github expert - is there a way to indicate favor of a PR without actively merging? Basically - is there something like "approve" on bitbucket?

**Comment by aelkner** [comment]
@cgreene, yes, I read the issues and was interested particularly in the JSON support mentioned by @awm33, so we will keep that in mind.  Perhaps we don't need a separate document store after all, but we can keep it in the diagram for now.

**Comment by dhimmel** [comment]
> is there a way to indicate favor of a PR without actively merging? 

Usually people note their peer review by comment. For example, the [bitcoin convention](https://github.com/bitcoin/bitcoin/blob/67caef673089aca2ffb95cd15b2cb056c96e5c30/CONTRIBUTING.md#peer-review) would be for you to write ACK. I find the short names potentially confusing, so for now we can just say: looks good to me and provide details on whether you've actually tested the changes.

**Comment by awm33** [comment]
@cgreene The way I do it at my company is assigning one or more people to do code review. Then each reviewer signs off on the PR after all outstanding issues from their comments are addressed. Signing off is usually is just with a "lgtm :+1:", "approved", etc

**Pull request merged**
