### PR TITLE
added djangorestframework support to the site

### PR DESCRIPTION
**Pull request by aelkner**
The rest api is providing a rest interface to admin objects (group, user) for now, and only to demonstrate how to successfully create serializers and ModelViewSets.  As we are creating more interesting models, we will be adding some of them to the rest api, and at that time we will have new examples, leaving us with the option to remove the entire admin_rest app should we feel it necessary.  For now only admin users will be able to see users and groups with the api.

### CODE REVIEW

**Comment by dhimmel** [comment]
I don't have the expertise to review this PR, but the code looks clean to me :+1:.

I did see there was Python 2 compatibility code, such as `from __future__ import unicode_literals`. Is this code 2/3 compatible? Once we settle #6 and if we choose Python 3, it may make sense to simplify the codebase by only supporting 3 -- e.g. future imports would no longer be needed.

**Comment by dhimmel** [comment]
@stephenshank @rzelayafavila @dcgoss @cgreene -- you are the four other people besides @aelkner who mentioned they have Django experience in [the introductions](https://github.com/cognoma/cognoma/issues/2). Could one of you look at this pull request?

**Comment by dcgoss** [comment]
Yep I'll take a look

**Comment by dcgoss** [comment]
Almost everything looks great to me. A few points:

Personally, I prefer having every API-related endpoint be under a /api/ url (ex. cognoma.org/api/....). This provides a good separation in case we ever want cognoma.org/users to return something other than JSON. 

I'm also personally not a fan of blank files (ex. models.py, admin.py). If we need them we can add them in later, but I find blank files just add entropy. 

Also, what is the significance behind the name `admin_rest`? Given the models involved (groups, users), it may be more semantically clear to name the app something like `users` user_rest`.

**Comment by aelkner** [comment]
I did mention that the api will be moved out of the root as soon as we come up with a home page and the pages under it.  At that time /users would return something other than what /api/users does, or as I had suggested /rest/users.  I'm not married to /rest and would be happy with /api when the time comes.

The empty files are not an issue in my opinion, they being a sign that the app was created with startapp.  As I mentioned this app could be removed after we get going with the real api, so let's not get bogged down with the contents of admin_rest.  It's just an end-to-end proof of rest support in the project.  That's all.  Although, if we do want to publish admin objects to an admin user, we could decide to keep it in.

We haven't even decided on our testing strategy, so there are no tests anywhere yet.  It is early, and going back and introducing tests will be a straightforward task to be done in the short term, but for now I'd like to get this into the code base to move things along.

**Comment by dcgoss** [comment]
Great, LGTM

**Comment by dhimmel** [comment]
> I'm not married to /rest and would be happy with /api when the time comes.

Does this pull request introduce the `/rest` endpoint? If so I think now is the appropriate time to discuss the best nomenclature.

I don't have a strong preference between `/rest` and `/api` but I prefer api because it's shorter and potentially more expressive.

> let's not get bogged down 

Unfortunately, the pull request model can lead to some delays and limits to the pace of development. However, these sacrifices are worth it in my opinion. We're not only looking to move forward quickly, but also be really rigorous so we get the details right and create a good learning environment.

**Comment by cgreene** [comment]
I agree that we should think about going to /api now so others can begin to see this structure.

Also - the task queue is now being discussed as https://github.com/cognoma/task-service - so we may not need to deal with celery here. Instead, we might want to start to focus on the API endpoints that face the UI first so that we can provide them to the web app team.

**Comment by dhimmel** [comment]
BTW, if you add commits to your branch (`master` in this case) that the pull request is based off of, the pull request updates. So if you wanted to change `rest` to `api`, you can add a commit and it will become part of this pull request.

**Comment by dhimmel** [comment]
@aelkner are you planning on making any updates to this pull request? It seems like changing `rest` to `api` has support. In general, it's good to make updates the review comments, unless you think they would make the pull request worse.

**Comment by aelkner** [comment]
I moved the rest api to /api, so there shouldn't be any reason not to merge the pull request now.

**Pull request merged**
